logging:
    level:
        blog: WARN
        org: WARN
        org.hibernate.SQL: DEBUG
pring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
spring:
    datasource:
        password: Ivaila12
        url: jdbc:mysql://localhost:3306/interviewExerc?useSSL=false&createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true
    mvc:
        hiddenmethod:
            filter:
                enabled: true
    servlet:
        multipart:
            max-file-size: 1MB
            max-request-size: 5MB
